# syntax=docker.io/docker/dockerfile:1

FROM node:22-alpine AS base

WORKDIR /app

RUN apk add --no-cache libc6-compat

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* pnpm-workspace.yaml* .npmrc* ./

RUN \
  if [ -f package-lock.json ]; then \ 
    npm ci; \
  elif [ -f pnpm-lock.yaml ]; then \ 
    corepack enable pnpm && \
    pnpm i --frozen-lockfile; \
  else \ 
    echo "Lockfile not found." && exit 1; \
  fi

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
